name: 'build-main'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
        
      - name: Use Node 15
        uses: actions/setup-node@v1
        with: 
          node-version: 15.x
      
      - name: Install dependencies
        run: npm install

      - name: Run all tests
        run: npm run test
